### ISSUE TITLE
Workload metrics

### ISSUE THREAD

**Issue by florinpapa** [Instagram/django-workload#11]
Hi,
Currently the workload metrics outputted are the Siege metrics (Transactions, Availability, Elapsed time, Data transferred, Response time, Transaction rate, Throughput, Concurrency, Successful Transactions, Failed transactions, Longest transaction, Shortest transaction). 

Another useful metric would be xx-th percentile (50, 75, 90, 95), which can be calculated based on the Siege output. Does this sound right? Aside from this, can anyone think of additional metrics we need in order to move this project closer to a benchmark?

**Comment by cooperlees** [comment]
P99 is always good to see as well.
I can't think of anything else off the top of my head here for now.

**Comment by florinpapa** [comment]
Added https://github.com/Instagram/django-workload/pull/17 for this.
