### ISSUE TITLE
Docker containers for the workload

### ISSUE THREAD

**Issue by florinpapa** [Instagram/django-workload#12]
Hi,
In order to ease the deployment effort and reflect real life usage, containerizing the workload seems to be the next step. For this, we propose creating Docker scripts that will deploy the Django Workload using Docker containers.

Please let me know how this sounds.

**Comment by cooperlees** [comment]
Docker seems to be the outside world hotness. If you'd like to make that all possible I'll happily review :D

**Comment by florinpapa** [comment]
I started working on this and the challenge I am facing is how to get a custom Python build from the host to the container. My approach is to copy the installation folder (some-folder) of:
```
./configure --prefix=some-folder
make
make install
```
into the container and use it to create a virtualenv. I ran into some issues building uwsgi because the LIBPL sysconfig variable was not pointing where it should be and solved the issue by creating some symbolic links. This is already implemented and needs some more testing before I can create a PR. Everything is automated, the user only needs to provide the path to the Python install folder described above.

Can anyone think of a better approach to get the custom built Python into the container or is my approach good enough?

**Comment by cooperlees** [comment]
Internally, due to having our own 'container'ing solution' our Docker skill sets are low.
I'd build a script to pull cpython sources + install the deps (via apt) to ensure the person building has all they need automatically too, then try and automate the copy into the container after starting it?
- I have no idea how to copy things into docker containers. It does keep like this building negates some of the helpfulness of the container. Are there Docker images/containers with the latest Python available?

**Comment by florinpapa** [comment]
You cannot install all the Python dependencies (from the requirements.txt file) without copying your custom python first, as you need to create the venv using that python and build all its dependencies using it because, for example, uwsgi usually links statically with that Python when it is built (and I assume other dependencies do the same).

As far as the automation goes, I created a script that takes care of everything. The user only needs to provide the path to the built Python (after make && make install), like this:
```
./build_containers.sh /path/to/desired/python
./run_containers.sh
```
- Because a developer will want to deploy their custom Python in order to measure the performance from source code chages, a pre-packaged Docker container with the latest Python will not solve the problem of having to copy and deploy a different Python.

**Comment by florinpapa** [comment]
Added https://github.com/Instagram/django-workload/pull/30

**Comment by florinpapa** [comment]
https://github.com/Instagram/django-workload/pull/30 was merged by @ambv
