### ISSUE TITLE
Include minimal correctness and functionality validation in the benchmark run

### ISSUE THREAD

**Issue by florinpapa** [Instagram/django-workload#13]
Hi,
At this point the workload does not include any functionality validation and there is no indicator whether it is doing the right thing. A proposal here is to activate Siege logging and parse the output in order to determine if the workload performs as intended.

The validation criteria includes counting the number of requests made to each URL to make sure the URL weights are respected and also check if all the requests have a 200 code, as they should. Please let me know if this sounds ok and I will create a PR.

**Comment by cooperlees** [comment]
Yes, validating + summarizing the siege output seems very sane to me!

**Comment by florinpapa** [comment]
Added https://github.com/Instagram/django-workload/pull/18 for this.
