### ISSUE TITLE
Implement new run rule

### ISSUE THREAD

**Issue by florinpapa** [Instagram/django-workload#15]
In order to get the most reliable results out of the Django Workload, we created a new run rule that by default runs the workload 7 times. Experiments so far indicate that the first run in the series renders less performance, due to services warming up (Cassandra, uWSGI, Memcached). For this reason, we chose to discard the run that renders the minimum throughput, but also the run with the maximum throughput, for fairness. An average of all the Siege metrics is displayed for the remaining 5 runs, together with the Relative Standard Deviation (RSD) of the runs, which is useful to indicate if everything went well. Experiments were also performed with 11 measurement runs, but workload stability did not change and did not justify the extra time. 

The entire Siege output from the 7 runs is stored to a file, for debugging purposes. The runner script was reimplemented in Python in order to be easily extended and a run time option was added that can specify running the workload only once (-s or --single), for anyone who doesn’t want to wait for 7 runs to finish.

This rule was chosen after performing an experiment on two BDW machines (test2-bdx-python and test3-bdx-python): 5 series of 11 runs were performed and the results are shown in the chart below. The results are normalized to the average obtained for the first 11-run series on test2-bdx-python. The run rule results are shown for 9 samples (11 runs from which the min and max were dropped) and 5 samples (7 runs from which the min and max were dropped). The results show that there is no significant difference in variation between 7 runs and 11 runs, therefore the new run rule will use 7 runs. This run rule shows that most of the results keep within 1% of the baseline on each machine. Please note that test3-bdx-python shows slightly lower throughput than test2-bdx-python, therefore the baseline is considered as the first data point on that particular machine.

![image](https://user-images.githubusercontent.com/2989160/28294011-253971fc-6b0c-11e7-9794-3f204e44c81e.png)

The results presented were collected after merging https://github.com/Instagram/django-workload/pull/3. A pull request was opened for this issue: https://github.com/Instagram/django-workload/pull/14

**Comment by cooperlees** [comment]
Will review the PR asap (hopefully by tomorrow 20170717)
