### ISSUE TITLE
Add TravisCI job(s) to django-workload

### ISSUE THREAD

**Issue by cooperlees** [Instagram/django-workload#16]
We should look at options of spinning up components and running some tests over them so we can be sure that diffs do not break things. At the moment we have nothing but manual testing. So this will be a multi phase effort:
- Unit tests on each components
- End to end testing of each component

**Comment by florinpapa** [comment]
I agree this is something we really should look into to make the review process easier. TravisCI looks great :) I will see how to integrate the project after adding the minimal validation decribed in https://github.com/Instagram/django-workload/issues/13.

**Comment by cooperlees** [comment]
We would have to start this and then you would be able to add to the testing with PRs. I will look at getting this done in the next few weeks:
https://docs.travis-ci.com/user/getting-started/

**Comment by KrishMunot** [comment]
This isn't actually necessary, since Phabricator sort of takes care of it imo

**Comment by cooperlees** [comment]
@KrishMunot - How does Phabricator take care of this for external contributors?

**Comment by cooperlees** [comment]
Lets not do this. We've got better with PRs + Phabricator CI showing on GitHUb since 2017.
