### ISSUE TITLE
Low request throughput due to profiling middleware

### ISSUE THREAD

**Issue by florinpapa** [Instagram/django-workload#5]
Hi,
The profiling middleware in django-workload/django_workload/middleware.py profiles every request to determine CPU and memory utilization. Disabling this profiling will almost triple the request throughput and eliminate the issue described in https://github.com/Instagram/django-workload/issues/4.
Profiling every request seems too expensive to be done in a real life scenario. Would it be a good idea to disable profiling completely, including statsd (via a flag), or switch to a sampling based profiling (every 10k or 100k requests) instead of what we have now? Does that reflect the real life deployment?
Also, is psutil the best way to do this?

**Comment by cooperlees** [comment]
As stated on 4, maybe start with sampling as we have sampled metrics sent all over the shop in production.

**Comment by suresh-srinivas** [comment]
@cooperlees and @florinpapa  I calculated the path length (the total instructions per transaction) it is 6.5x more for the profiling case (with a 20% of the throughput of no profiling) than the no profiling . I strongly recommend against doing any profiling for the workload measurement if the overhead is so many instructions. The memory profiling particularly seems to be very expensive and is hardly changing. Also it tends to create a lot of contention with all the processes doing it. Even with sampling that will not be solved. Maybe sampling with only one uWSGI process doing profiling might be the way to reduce both the overhead and the contention.

**Comment by florinpapa** [comment]
Added https://github.com/Instagram/django-workload/pull/25 which implements sample-based profiling every 1000 requests.

**Comment by cooperlees** [comment]
We now have tweak-able sampling rate for expensive statistics.
