### ISSUE TITLE
Cassandra performance tuning

### ISSUE THREAD

**Issue by florinpapa** [Instagram/django-workload#6]
Hi,
We are observing high CPU utilization coming from Cassandra when the default configuration is used. The workload throughput will usually increase and the Cassandra CPU utilization will be reduced if some of the settings described here are followed:
http://docs.datastax.com/en/dse/5.1/dse-admin/datastax_enterprise/config/configRecommendedSettings.html

However, the settings described above do not work in all cases and some Cassandra and JVM configs need to be tweaked depending on the system in case in order to get the best performance. For the Cassandra config, the following flags in /etc/cassandra/cassandra.yaml showed performance impact:
```
concurrent_reads: 32
concurrent_writes: 32
concurrent_counter_writes: 32
concurrent_materialized_view_writes: 32
```
For the JVM options, the heap size can impact performance. Setting the heap size to half the available memory in the system will generally render good performance. For example, if you have a system with 128GB available memory, setting the heap size to 64GB can be done by setting the following flags in /etc/cassandra/jvm.options:
```
-Xms64G
-Xmx64G
```
Please let me know if including these settings in the Django Workload sounds like a good idea and I will create a PR.

**Comment by cooperlees** [comment]
I'll chase down our internal Cassandra experts for you and get them to comment.

**Comment by DikangGu** [comment]
Hi florinpapa, I'm working on Cassandra in Instagram. There are lots of settings in Cassandra JVM. Which version of Cassandra are you using? What's the JVM version and type of GC you use?

Normally, we use some settings like this:
concurrent_reads: 64
concurrent_writes: 128
concurrent_counter_writes: 128

We do not use materialized view, it's not stabilized yet.

For JVM settings, there are even more settings to tune, and for different workload, the settings may different. We normally use settings like this:

-XX:+CMSClassUnloadingEnabled -XX:+UseThreadPriorities -XX:ThreadPriorityPolicy=42 -Xms65536M -Xmx65536M -Xmn16384M -XX:+HeapDumpOnOutOfMemoryError -Xss256k -XX:StringTableSize=1000003 -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:SurvivorRatio=4 -XX:CMSInitiatingOccupancyFraction=60 -XX:+UseCMSInitiatingOccupancyOnly -XX:+CMSScavengeBeforeRemark -XX:CMSMaxAbortablePrecleanTime=60000 -XX:CMSWaitDuration=30000 -XX:+CMSParallelInitialMarkEnabled -XX:+CMSEdenChunksRecordAlways -XX:+UseCondCardMark -XX:MaxTenuringThreshold=2 -XX:-UseBiasedLocking -XX:+UseTLAB -XX:+ResizeTLAB -XX:+PerfDisableSharedMem -XX:+AlwaysPreTouch -XX:+UnlockDiagnosticVMOptions -XX:ParGCCardsPerStrideChunk=4096 -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -XX:+PrintPromotionFailure -XX:+PrintClassHistogramBeforeFullGC -XX:+PrintClassHistogramAfterFullGC -Xloggc:/var/log/cassandra/gc.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=2 -XX:GCLogFileSize=10M

**Comment by florinpapa** [comment]
Hi DikangGu, thank you for your response. We are using Cassandra 3.10, java version:

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

The GC we are using is G1, as recommended here http://docs.datastax.com/en/dse/5.1/dse-admin/datastax_enterprise/config/configRecommendedSettings.html. Is CMS a better choice than G1? I see in the settings that you posted that you use CMS.

**Comment by DikangGu** [comment]
Yeah, we are using CMS, it works better for our workload. 

For Cassandra version, I think at this moment, 3.0.14 is more stable than higher 3.X versions. If you do not need the features in 3.X, you should try 3.0.14.

**Comment by florinpapa** [comment]
This is great info, thanks. We will try out 3.0.14 and the settings you recommended and see how the workload behaves.

**Comment by florinpapa** [comment]
Switching to Cassandra 3.0.14 and applying the suggested settings did bring an increase in RPS compared to Cassandra 3.10. Thank you DikangGu for the info. Created https://github.com/Instagram/django-workload/pull/19 for this.
