### ISSUE TITLE
Django Workload logging

### ISSUE THREAD

**Issue by florinpapa** [Instagram/django-workload#7]
Hi,
At this point logging is activated for Memcached (ran with “-vv” in the runner script), uWSGI, Cassandra and Siege.
Would it still be accurate to disable logging from Memcached, uWSGI and Cassandra? Siege logging is done client side and it is a good indicator whether everything works, so it should probably exist.
Also, the docker-statsd container’s default configuration will cause filling up the disk space of the host because it records unnecessary metrics that should be blacklisted and the storage schema can be updated to use less space. Thank you Martijn Pieters for this find. If it is ok, I will create a PR to address this.

**Comment by cooperlees** [comment]
This all sounds reasonable to disable. It would be nice to document how to turn this back on for debugging when things break on new software releases etc.

**Comment by florinpapa** [comment]
Added https://github.com/Instagram/django-workload/pull/20 for this.

**Comment by florinpapa** [comment]
Logging was disabled in the workload and instructions on how to turn logging back on was added.
