### ISSUE TITLE
Default benchmarking parameters

### ISSUE THREAD

**Issue by florinpapa** [Instagram/django-workload#9]
Hi,
The current default benchmarking parameters (uWSGI concurrent workers - 4, Memcached number of threads - 4 and Siege concurrency - 144) are too low for running properly on a powerful server. I suggest that we increase these values to:
```
uWSGI concurrent workers – 88
Memcached threads – 16
Siege Concurrency – 180
```
These numbers were suitable for benchmarking on a 2-socket Broadwell system and obtain a CPU utilization of over 85%. Please let me know how this sounds and I will open a PR.

**Comment by cooperlees** [comment]
Go for it. This will predominately be used on larger machines - Just make note in README why we have done this.

**Comment by florinpapa** [comment]
Added https://github.com/Instagram/django-workload/pull/23 for this.

**Comment by florinpapa** [comment]
These changes were merged.
